# Generated by Django 2.2.10 on 2020-08-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200815_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
