# Generated by Django 2.2.10 on 2020-08-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200815_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thematic',
            options={'verbose_name': 'Тэги', 'verbose_name_plural': 'Тэг'},
        ),
    ]
