# Generated by Django 2.2.10 on 2020-08-19 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200819_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Thematic', verbose_name='РАЗДЕЛ'),
        ),
    ]
