# Generated by Django 2.2.10 on 2020-08-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200819_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='thematic',
            name='tags',
            field=models.ManyToManyField(through='articles.Membership', to='articles.Article'),
        ),
    ]
