# Generated by Django 2.2.10 on 2020-08-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200820_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='main_tag',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
